/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AudioMediaPort extends AudioMedia {
  private transient long swigCPtr;

  protected AudioMediaPort(long cPtr, boolean cMemoryOwn) {
    super(pjsua2JNI.AudioMediaPort_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioMediaPort obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AudioMediaPort(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsua2JNI.AudioMediaPort_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsua2JNI.AudioMediaPort_change_ownership(this, swigCPtr, true);
  }

  public AudioMediaPort() {
    this(pjsua2JNI.new_AudioMediaPort(), true);
    pjsua2JNI.AudioMediaPort_director_connect(this, swigCPtr, true, true);
  }

  public void createPort(String name, MediaFormatAudio fmt) throws java.lang.Exception {
    pjsua2JNI.AudioMediaPort_createPort(swigCPtr, this, name, MediaFormatAudio.getCPtr(fmt), fmt);
  }

  public void onFrameRequested(MediaFrame frame) {
    if (getClass() == AudioMediaPort.class) pjsua2JNI.AudioMediaPort_onFrameRequested(swigCPtr, this, MediaFrame.getCPtr(frame), frame); else pjsua2JNI.AudioMediaPort_onFrameRequestedSwigExplicitAudioMediaPort(swigCPtr, this, MediaFrame.getCPtr(frame), frame);
  }

  public void onFrameReceived(MediaFrame frame) {
    if (getClass() == AudioMediaPort.class) pjsua2JNI.AudioMediaPort_onFrameReceived(swigCPtr, this, MediaFrame.getCPtr(frame), frame); else pjsua2JNI.AudioMediaPort_onFrameReceivedSwigExplicitAudioMediaPort(swigCPtr, this, MediaFrame.getCPtr(frame), frame);
  }

}
