/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class MediaFrame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MediaFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_MediaFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    pjsua2JNI.MediaFrame_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return pjsua2JNI.MediaFrame_type_get(swigCPtr, this);
  }

  public void setBuf(ByteVector value) {
    pjsua2JNI.MediaFrame_buf_set(swigCPtr, this, ByteVector.getCPtr(value), value);
  }

  public ByteVector getBuf() {
    long cPtr = pjsua2JNI.MediaFrame_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ByteVector(cPtr, false);
  }

  public void setSize(long value) {
    pjsua2JNI.MediaFrame_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return pjsua2JNI.MediaFrame_size_get(swigCPtr, this);
  }

  public MediaFrame() {
    this(pjsua2JNI.new_MediaFrame(), true);
  }

}
